# Specify docker-compose version.
version: '3'

# Specify containers that will be built.
services:
  # Nginx Service
  nginx:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./code/:/usr/share/nginx/html/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - duet
    restart: always
    networks:
      - hitch-network

  # MySQL Service
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: db
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: hitch
      MYSQL_ROOT_PASSWORD: helios
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: always
    depends_on:
      - nginx
    networks:
     - hitch-network

  # DUET Service
  duet:
    build:
      context: .
      dockerfile: Dockerfile.duet
    container_name: duet
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - ./duet/:/duet/
    environment:
      - FLASK_APP=/duet/duet.py
    command: flask run --host=0.0.0.0
    # depends_on:
    #   - nginx
    networks:
     hitch-network:
      aliases:
        - docker-duet

# Specify docker networks for container communication.
networks:
 hitch-network:

