# Specify docker-compose version.
version: '3'

# Specify containers that will be built.
services:
  # Nginx Service
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      # Include NGINX configuration
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      # Include HTML/CSS/Js files
      - ./code/:/usr/share/nginx/html/
      # Map logs to host machine
      - ./log/nginx/:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - duet
    restart: always
    networks:
      - hitch-network

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: php
    volumes:
      - ./code:/var/www/html/
      - ./conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      hitch-network:
        aliases:
         - docker-php


  # MySQL Service
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: db
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: hitch
      MYSQL_USER: hitch
      MYSQL_ROOT_PASSWORD: helios
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: always
    depends_on:
      - nginx
    networks:
     - hitch-network
    command: ['--default-authentication-plugin=mysql_native_password']

  # DUET Service
  duet:
    build:
      context: .
      dockerfile: Dockerfile.duet
    container_name: duet
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - ./duet/:/duet/
    environment:
      - FLASK_APP=/duet/duet.py
    command: flask run --host=0.0.0.0
    networks:
      hitch-network:
        aliases:
          - docker-duet

# Specify docker networks for container communication.
networks:
  hitch-network:
    driver: bridge

