# Specify docker-compose version.
version: '3'

# Specify containers that will be built.
services:
  # Nginx Service
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - hitch-network

  # MySQL Service
  mysql:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hitch
      MYSQL_ROOT_PASSWORD: helios
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: always
    depends_on:
      - nginx
    networks:
      - hitch-network

  # DUET Service
  # duet:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: Dockerfile.duet
  #   container_name: duet
  #   restart: always
  #   depends_on:
  #     - nginx
  #   networks:
  #     - hitch-network

# Specify docker networks for container communication.
networks:
  hitch-network:
    driver: bridge
