# Django DUET Api Dockerfile
# Build using Python 3.7 docker image.
FROM python:3.7

# Force stdout and stderr streams to print unbuffered rather than spooling.
ENV PYTHONUNBUFFERED 1

# Install Python requirements for DUET.
RUN pip install flask flask_api
