FROM nginx

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY conf/default.conf /etc/nginx/conf.d/default.conf

COPY code /usr/share/nginx/html

EXPOSE 80

# Start Nginx when the container has provisioned.
CMD ["nginx", "-g", "daemon off;"]
