# Django DUET Api Dockerfile
FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /duet
WORKDIR /duet
ADD ./duet/requirements.txt /duet/
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY duet/ /duet/
