version: '3.6'
services:

  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    restart: unless-stopped
    #volumes:
    #  - ./code:/usr/share/nginx/html/
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hitch
      MYSQL_ROOT_PASSWORD: helios
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: unless-stopped
    volumes:
      - ./db_data/:/docker-entrypoint-initdb.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
