var modules =
[
    [ "Meta-types of display implementations", "group___d_i_s_p_l_a_y___t_y_p_e_s.html", "group___d_i_s_p_l_a_y___t_y_p_e_s" ],
    [ "Display_control command and status codes", "group___d_i_s_p_l_a_y___c_o_n_t_r_o_l.html", "group___d_i_s_p_l_a_y___c_o_n_t_r_o_l" ],
    [ "SPI_control command and status codes", "group___s_p_i___c_o_n_t_r_o_l.html", "group___s_p_i___c_o_n_t_r_o_l" ],
    [ "UART_control command and status codes", "group___u_a_r_t___c_o_n_t_r_o_l.html", "group___u_a_r_t___c_o_n_t_r_o_l" ],
    [ "BLE GAP Constants and Structures", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html", "group___b_l_e___g_a_p___d_e_f_i_n_e_s" ],
    [ "GAP API Functions", "group___g_a_p___a_p_i.html", "group___g_a_p___a_p_i" ],
    [ "GAP Bond Manager Constants", "group___g_a_p_b_o_n_d___c_o_n_s_t_a_n_t_s___n_a_m_e.html", null ],
    [ "GAP Bond Manager Parameters", "group___g_a_p_b_o_n_d___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html", "group___g_a_p_b_o_n_d___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s" ],
    [ "GAP Bond Manager Pairing Modes", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___m_o_d_e___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___m_o_d_e___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager I/O Capabilities", "group___g_a_p_b_o_n_d___i_o___c_a_p___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___i_o___c_a_p___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager Key Distribution", "group___g_a_p_b_o_n_d___k_e_y___d_i_s_t___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___k_e_y___d_i_s_t___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager Pairing States", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___s_t_a_t_e___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___p_a_i_r_i_n_g___s_t_a_t_e___d_e_f_i_n_e_s" ],
    [ "Pairing failure status values", "group___s_m_p___p_a_i_r_i_n_g___f_a_i_l_e_d___d_e_f_i_n_e_s.html", "group___s_m_p___p_a_i_r_i_n_g___f_a_i_l_e_d___d_e_f_i_n_e_s" ],
    [ "Bonding Failure Actions", "group___g_a_p_b_o_n_d___b_o_n_d_i_n_g___f_a_i_l_u_r_e___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___b_o_n_d_i_n_g___f_a_i_l_u_r_e___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager Secure Connections options", "group___g_a_p_b_o_d___s_e_c_u_r_e___c_o_n_n_e_c_t_i_o_n_s___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_d___s_e_c_u_r_e___c_o_n_n_e_c_t_i_o_n_s___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager ECC Re-use count before regeneration", "group___g_a_p_b_o_n_d___e_c_c_k_e_y___r_e_g_e_n___p_o_l_i_c_y___d_e_f_i_n_e_s.html", "group___g_a_p_b_o_n_d___e_c_c_k_e_y___r_e_g_e_n___p_o_l_i_c_y___d_e_f_i_n_e_s" ],
    [ "GAP Bond Manager API Functions", "group___g_a_p_r_o_l_e_s___b_o_n_d_m_g_r___a_p_i.html", "group___g_a_p_r_o_l_e_s___b_o_n_d_m_g_r___a_p_i" ],
    [ "GATT Attribute Access Permissions Bit Fields", "group___g_a_t_t___p_e_r_m_i_t___b_i_t_m_a_p_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___p_e_r_m_i_t___b_i_t_m_a_p_s___d_e_f_i_n_e_s" ],
    [ "GATT Maximum Number of Prepare Writes", "group___g_a_t_t___n_u_m___p_r_e_p_a_r_e___w_r_i_t_e_s___d_e_f_i_n_e_s.html", "group___g_a_t_t___n_u_m___p_r_e_p_a_r_e___w_r_i_t_e_s___d_e_f_i_n_e_s" ],
    [ "GATT Encryption Key Size Limits", "group___g_a_t_t___e_n_c_r_y_p_t___k_e_y___s_i_z_e___d_e_f_i_n_e_s.html", "group___g_a_t_t___e_n_c_r_y_p_t___k_e_y___s_i_z_e___d_e_f_i_n_e_s" ],
    [ "GATT Maximum Attribute Value Length", "group___g_a_t_t___m_a_x___a_t_t_r___s_i_z_e___d_e_f_i_n_e_s.html", "group___g_a_t_t___m_a_x___a_t_t_r___s_i_z_e___d_e_f_i_n_e_s" ],
    [ "GATT Client API Functions", "group___g_a_t_t___c_l_i_e_n_t___a_p_i.html", "group___g_a_t_t___c_l_i_e_n_t___a_p_i" ],
    [ "GATT Server API Functions", "group___g_a_t_t___s_e_r_v_e_r___a_p_i.html", "group___g_a_t_t___s_e_r_v_e_r___a_p_i" ],
    [ "GATT Server Sub-Procedure API Functions", "group___g_a_t_t___s_e_r_v_e_r___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i.html", "group___g_a_t_t___s_e_r_v_e_r___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i" ],
    [ "GATT Client Sub-Procedure API Functions", "group___g_a_t_t___c_l_i_e_n_t___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i.html", "group___g_a_t_t___c_l_i_e_n_t___s_u_b___p_r_o_c_e_d_u_r_e___a_p_i" ],
    [ "Client and Server Common API Functions", "group___g_a_t_t___c_o_m_m_o_n___a_p_i.html", "group___g_a_t_t___c_o_m_m_o_n___a_p_i" ],
    [ "GATT Buffer Management API Functions", "group___g_a_t_t___b_m___a_p_i.html", "group___g_a_t_t___b_m___a_p_i" ],
    [ "GATT Flow Control API Functions", "group___g_a_t_t___f_l_o_w___c_t_r_l___a_p_i.html", "group___g_a_t_t___f_l_o_w___c_t_r_l___a_p_i" ],
    [ "Bluetooth predefined UUID", "group___b_t___b_a_s_e___u_u_i_d___g_r_p.html", "group___b_t___b_a_s_e___u_u_i_d___g_r_p" ],
    [ "GAP Role Parameters", "group___g_a_p_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s.html", "group___g_a_p_r_o_l_e___p_r_o_f_i_l_e___p_a_r_a_m_e_t_e_r_s" ],
    [ "GAP Peripheral Role API Functions", "group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___a_p_i.html", "group___g_a_p_r_o_l_e_s___p_e_r_i_p_h_e_r_a_l___a_p_i" ],
    [ "ECC_STATUS", "group___e_c_c___s_t_a_t_u_s.html", "group___e_c_c___s_t_a_t_u_s" ],
    [ "RF_EventMask", "group___r_f___event_mask.html", "group___r_f___event_mask" ],
    [ "RF_CTRL", "group___r_f___c_t_r_l.html", "group___r_f___c_t_r_l" ],
    [ "TRNG_STATUS", "group___t_r_n_g___s_t_a_t_u_s.html", "group___t_r_n_g___s_t_a_t_u_s" ],
    [ "DMA_STATUS", "group___d_m_a___s_t_a_t_u_s.html", null ],
    [ "DMA_CMD", "group___d_m_a___c_m_d.html", null ]
];